[tool.poetry]
name = "python-fastapi-boilerplate"
version = "0.1.0"
description = "Complete FastAPI boilerplate with async SQLAlchemy, Alembic, Docker, CI and pre-commit."
authors = ["Pratik <pratikahir001@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.116.1"
uvicorn = {extras = ["standard"], version = "^0.35.0"}
python-multipart = "^0.0.20"
pydantic = "^2.11.7"
pydantic-settings = "^2.1.0"
ujson = "^5.10.0"
yarl = "^1.20.1"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
isort = "^5.13.2"
flake8 = "^7.0.0"
mypy = "^1.9.0"
pytest = "^8.1.1"
pytest-asyncio = "^0.23.6"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
